import test from 'node:test';
import assert from 'node:assert/strict';
import { createBookingAtomic, SlotConflictError } from '../src/services/bookings.js';

const shop = { _id: 'shop1', timezone: 'Asia/Shanghai', email: '' };
const rule = {
  _id: 'rule1', enabled: true, productId: 'product1', productTitle: 'Fitting', duration: 60, buffer: 0,
  location: 'Showroom', staff: 'Sarah', customQuestions: [],
  weeklyAvailability: [{ weekday: 1, enabled: true, windows: [{ start: '09:00', end: '11:00' }] }]
};
const input = { date: '2026-08-24', time: '09:00', customer: { name: 'Jane', email: 'jane@example.com', phone: '' }, note: '', answers: [] };

test('booking creation carries denormalized rule details', async () => {
  let document;
  const BookingModel = { async create(value) { document = { _id: 'b1', ...value }; return document; } };
  const booking = await createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => ({ skipped: true }) });
  assert.equal(booking.slotKey, '2026-08-24T09:00');
  assert.equal(booking.location, 'Showroom');
});

test('Mongo duplicate-key error becomes an explicit slot conflict', async () => {
  const BookingModel = { async create() { throw Object.assign(new Error('duplicate'), { code: 11000 }); } };
  await assert.rejects(() => createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => {} }), SlotConflictError);
});

test('server rejects a time that was not generated by the rule', async () => {
  const BookingModel = { async create() { throw new Error('must not insert'); } };
  await assert.rejects(() => createBookingAtomic({ shop, rule, input: { ...input, time: '09:30' }, BookingModel, notify: async () => {} }), /not available/);
});
