import test from 'node:test';
import assert from 'node:assert/strict';
import { cancelManagedBooking, createBookingAtomic, hashManagementToken, rescheduleManagedBooking, SlotConflictError } from '../src/services/bookings.js';

const shop = { _id: 'shop1', timezone: 'Asia/Shanghai', email: '' };
const rule = {
  _id: 'rule1', enabled: true, productId: 'product1', productTitle: 'Fitting', duration: 60, buffer: 0,
  location: 'Showroom', staff: 'Sarah', customQuestions: [],
  weeklyAvailability: [{ weekday: 1, enabled: true, windows: [{ start: '09:00', end: '11:00' }] }]
};
const input = { date: '2026-08-24', time: '09:00', customer: { name: 'Jane', email: 'jane@example.com', phone: '' }, note: '', answers: [] };

test('booking creation carries denormalized rule details', async () => {
  let document;
  const BookingModel = { async create(value) { document = { _id: 'b1', ...value }; return document; } };
  const { booking, managementToken } = await createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => ({ skipped: true }) });
  assert.equal(booking.slotKey, '2026-08-24T09:00');
  assert.equal(booking.location, 'Showroom');
  assert.match(managementToken, /^[A-Za-z0-9_-]{43}$/);
  assert.equal(booking.managementTokenHash, hashManagementToken(managementToken));
});

test('Mongo duplicate-key error becomes an explicit slot conflict', async () => {
  const BookingModel = { async create() { throw Object.assign(new Error('duplicate'), { code: 11000 }); } };
  await assert.rejects(() => createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => {} }), SlotConflictError);
});

test('server rejects a time that was not generated by the rule', async () => {
  const BookingModel = { async create() { throw new Error('must not insert'); } };
  await assert.rejects(() => createBookingAtomic({ shop, rule, input: { ...input, time: '09:30' }, BookingModel, notify: async () => {} }), /not available/);
});

test('customer cancellation requires the hashed management token', async () => {
  const token = 'a'.repeat(43);
  let filter;
  const BookingModel = { async findOneAndUpdate(query) { filter = query; return { _id: 'b1', status: 'cancelled' }; } };
  const booking = await cancelManagedBooking({ bookingId: 'b1', token, BookingModel });
  assert.equal(booking.status, 'cancelled');
  assert.equal(filter.managementTokenHash, hashManagementToken(token));
  assert.notEqual(filter.managementTokenHash, token);
});

test('customer reschedule validates the rule and atomically moves the slot', async () => {
  const token = 'b'.repeat(43);
  let update;
  const existing = { _id: 'b1', shopId: 'shop1', ruleId: 'rule1', status: 'confirmed', slotKey: '2026-08-24T09:00' };
  const BookingModel = {
    async findOne() { return existing; },
    async findOneAndUpdate(filter, value) { update = { filter, value }; return { ...existing, ...value }; }
  };
  const RuleModel = { async findOne() { return rule; } };
  await rescheduleManagedBooking({ bookingId: 'b1', token, date: '2026-08-24', time: '10:00', BookingModel, RuleModel });
  assert.equal(update.filter.slotKey, '2026-08-24T09:00');
  assert.equal(update.value.slotKey, '2026-08-24T10:00');
});
