import test from 'node:test';
import assert from 'node:assert/strict';
import { cancelManagedBooking, createBookingAtomic, getLegacyBookingStatus, getManagedAvailability, hashManagementToken, rescheduleManagedBooking, SlotConflictError, updateBookingByMerchant } from '../src/services/bookings.js';

const shop = { _id: 'shop1', timezone: 'Asia/Shanghai', email: '' };
const rule = {
  _id: 'rule1', enabled: true, productId: 'product1', productTitle: 'Fitting', duration: 60, buffer: 0,
  location: 'Showroom', staff: 'Sarah', customQuestions: [],
  weeklyAvailability: [{ weekday: 1, enabled: true, windows: [{ start: '09:00', end: '11:00' }] }]
};
const input = { date: '2026-08-24', time: '09:00', customer: { name: 'Jane', email: 'jane@example.com', phone: '' }, note: '', answers: [] };
const beforeOpening = new Date('2026-08-23T16:00:00.000Z');

test('booking creation carries denormalized rule details', async () => {
  let document;
  const BookingModel = { async create(value) { document = { _id: 'b1', ...value }; return document; } };
  const { booking, managementToken } = await createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => ({ skipped: true }), now: beforeOpening });
  assert.equal(booking.slotKey, '2026-08-24T09:00');
  assert.equal(booking.location, 'Showroom');
  assert.match(managementToken, /^[A-Za-z0-9_-]{43}$/);
  assert.equal(booking.managementTokenHash, hashManagementToken(managementToken));
});

test('Mongo duplicate-key error becomes an explicit slot conflict', async () => {
  const BookingModel = { async create() { throw Object.assign(new Error('duplicate'), { code: 11000 }); } };
  await assert.rejects(() => createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => {}, now: beforeOpening }), SlotConflictError);
});

test('server rejects a time that was not generated by the rule', async () => {
  const BookingModel = { async create() { throw new Error('must not insert'); } };
  await assert.rejects(() => createBookingAtomic({ shop, rule, input: { ...input, time: '09:30' }, BookingModel, notify: async () => {}, now: beforeOpening }), /unavailable/);
});

test('server rejects a generated slot that has already passed in the store time zone', async () => {
  const BookingModel = { async create() { throw new Error('must not insert'); } };
  const now = new Date('2026-08-24T02:30:00.000Z');
  await assert.rejects(
    () => createBookingAtomic({ shop, rule, input, BookingModel, notify: async () => {}, now }),
    error => error.code === 'SLOT_UNAVAILABLE' && /store time zone/.test(error.message)
  );
});

test('customer cancellation requires the hashed management token', async () => {
  const token = 'a'.repeat(43);
  let filter;
  const current = { _id: 'b1', status: 'confirmed', slotKey: '2026-08-24T09:00', date: '2026-08-24', time: '09:00' };
  const BookingModel = { async findOne() { return current; }, async findOneAndUpdate(query) { filter = query; return { ...current, status: 'cancelled' }; } };
  const booking = await cancelManagedBooking({ bookingId: 'b1', token, BookingModel, notify: async () => ({ skipped: true }) });
  assert.equal(booking.status, 'cancelled');
  assert.equal(filter.managementTokenHash, hashManagementToken(token));
  assert.notEqual(filter.managementTokenHash, token);
});

test('booking mutations append an audit event without overwriting history', async () => {
  let update;
  const token = 'e'.repeat(43);
  const existing = { _id: 'b1', shopId: 'shop1', ruleId: 'rule1', status: 'confirmed', slotKey: '2026-08-24T09:00', date: '2026-08-24', time: '09:00', timezone: 'Asia/Shanghai', customerRescheduleCount: 0, location: 'Showroom', staff: 'Sarah' };
  const BookingModel = {
    async findOne() { return existing; },
    async findOneAndUpdate(filter, value) { update = value; return { ...existing, ...value.$set }; }
  };
  const RuleModel = { async findOne() { return rule; } };
  await rescheduleManagedBooking({ bookingId: 'b1', token, date: '2026-08-24', time: '10:00', BookingModel, RuleModel, notify: async () => ({ skipped: true }), now: beforeOpening });
  assert.equal(update.$push.events.type, 'customer_rescheduled');
  assert.equal(update.$push.events.from.time, '09:00');
  assert.equal(update.$push.events.to.time, '10:00');
});

test('legacy receipt status lookup returns only identity and status', async () => {
  let filter;
  let projection;
  const BookingModel = { async findOne(query, fields) { filter = query; projection = fields; return { _id: 'b1', status: 'cancelled', customer: { email: 'private@example.com' } }; } };
  const result = await getLegacyBookingStatus({ bookingId: 'b1', shopObjectId: 'shop1', productId: 'product1', BookingModel });
  assert.deepEqual(result, { id: 'b1', status: 'cancelled' });
  assert.deepEqual(filter, { _id: 'b1', shopId: 'shop1', productId: 'product1' });
  assert.deepEqual(projection, { _id: 1, status: 1 });
  assert.equal('customer' in result, false);
});

test('customer reschedule validates the rule and atomically moves the slot', async () => {
  const token = 'b'.repeat(43);
  let update;
  const existing = { _id: 'b1', shopId: 'shop1', ruleId: 'rule1', status: 'confirmed', slotKey: '2026-08-24T09:00', timezone: 'Asia/Shanghai', customerRescheduleCount: 0 };
  const BookingModel = {
    async findOne() { return existing; },
    async findOneAndUpdate(filter, value) { update = { filter, value }; return { ...existing, ...value.$set, customerRescheduleCount: 1 }; }
  };
  const RuleModel = { async findOne() { return rule; } };
  await rescheduleManagedBooking({ bookingId: 'b1', token, date: '2026-08-24', time: '10:00', BookingModel, RuleModel, notify: async () => ({ skipped: true }), now: beforeOpening });
  assert.equal(update.filter.slotKey, '2026-08-24T09:00');
  assert.equal(update.value.$set.slotKey, '2026-08-24T10:00');
  assert.equal(update.value.$inc.customerRescheduleCount, 1);
});

test('customer cannot reschedule more than once', async () => {
  const BookingModel = { async findOne() { return { _id: 'b1', status: 'confirmed', customerRescheduleCount: 1 }; } };
  await assert.rejects(
    () => rescheduleManagedBooking({ bookingId: 'b1', token: 'c'.repeat(43), date: '2026-08-24', time: '10:00', BookingModel }),
    error => error.code === 'RESCHEDULE_LIMIT' && error.status === 409
  );
});

test('managed availability authenticates the private token and removes booked slots', async () => {
  const token = 'd'.repeat(43);
  let bookingQuery;
  const current = { _id: 'b1', shopId: 'shop1', ruleId: 'rule1', status: 'confirmed', timezone: 'Asia/Shanghai' };
  const BookingModel = {
    async findOne(query) { bookingQuery = query; return current; },
    find() { return { async distinct() { return ['09:00']; } }; }
  };
  const RuleModel = { async findOne() { return rule; } };
  const result = await getManagedAvailability({ bookingId: 'b1', token, date: '2026-08-24', BookingModel, RuleModel, now: beforeOpening });
  assert.equal(bookingQuery.managementTokenHash, hashManagementToken(token));
  assert.deepEqual(result, { date: '2026-08-24', slots: ['10:00'] });
});

test('merchant can edit a confirmed booking without consuming customer change allowance', async () => {
  let update;
  let notified = false;
  const existing = { _id: 'b1', shopId: 'shop1', ruleId: 'rule1', status: 'confirmed', slotKey: '2026-08-24T09:00', timezone: 'Asia/Shanghai', customerRescheduleCount: 1 };
  const BookingModel = {
    async findOne() { return existing; },
    async findOneAndUpdate(filter, value) { update = { filter, value }; return { ...existing, ...value.$set }; }
  };
  const RuleModel = { async findOne() { return rule; } };
  const result = await updateBookingByMerchant({
    shopObjectId: 'shop1', bookingId: 'b1', input: { date: '2026-08-24', time: '10:00', location: 'Room B', staff: 'Alex' },
    BookingModel, RuleModel, notify: async () => { notified = true; return { skipped: true }; }, now: beforeOpening
  });
  assert.equal(update.value.$set.slotKey, '2026-08-24T10:00');
  assert.equal('$inc' in update.value, false);
  assert.equal(result.booking.customerRescheduleCount, 1);
  assert.equal(notified, true);
});
