import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = path => readFile(new URL(path, import.meta.url), 'utf8');

test('v0.8.1.4.2 Theme Extension uses SHOPLINE-supported TTF fonts instead of WOFF2', async () => {
  const [modalCss, pageCss, embedCss, syncScript, pkg] = await Promise.all([
    read('../theme-extension-source/public/appointment-lite.css'),
    read('../theme-extension-source/public/appointment-lite-page.css'),
    read('../theme-extension-source/public/appointment-lite-embed.css'),
    read('../scripts/sync-theme-fonts.mjs'),
    read('../package.json')
  ]);
  for (const css of [modalCss, pageCss, embedCss]) {
    assert.match(css, /\.\/al-jost-600\.ttf/);
    assert.match(css, /\.\/al-poppins-400\.ttf/);
    assert.match(css, /format\("truetype"\)/);
    assert.doesNotMatch(css, /\.woff2|format\("woff2"\)/);
  }
  assert.match(syncScript, /Jost_600SemiBold\.ttf/);
  assert.match(syncScript, /Poppins_400Regular\.ttf/);
  assert.match(syncScript, /remove fonts generated by older releases/i);
  assert.match(syncScript, /woff2\|woff\|ttf/);
  assert.match(pkg, /"@expo-google-fonts\/jost": "0\.4\.2"/);
  assert.match(pkg, /"@expo-google-fonts\/poppins": "0\.4\.1"/);
});
