import { Booking } from '../models/Booking.js';
import { Shop } from '../models/Shop.js';
import { EmailReminderDelivery } from '../models/EmailReminderDelivery.js';
import { normalizeEmailSettings, merchantNotificationRecipients } from '../lib/email-settings.js';
import { reminderIsDue, reminderOccurrences, wallTimeToInstant } from '../lib/reminder-time.js';
import { sendCustomerUpcomingReminder, sendMerchantUpcomingReminder } from './email.js';
const RUN_INTERVAL_MS=5*60*1000, INITIAL_DELAY_MS=15*1000, CLAIM_STALE_MS=15*60*1000;
const utcDateShift=(now,days)=>{const d=new Date(now);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
const bookingForOccurrence=(booking,occurrence)=>(booking.bookingMode||'slot')==='multi_slot'?{...booking,bookingMode:'slot',date:occurrence.date,time:occurrence.time,occurrences:[]}:booking;
async function ensureDelivery(Model,booking,occurrence,audience,leadHours){const key={bookingId:booking._id,occurrenceKey:occurrence.occurrenceKey,audience};try{return await Model.findOneAndUpdate(key,{$setOnInsert:{...key,shopId:booking.shopId,leadHours,status:'pending'}},{upsert:true,new:true,setDefaultsOnInsert:true}).lean();}catch(error){if(error?.code!==11000)throw error;return Model.findOne(key).lean();}}
async function claimDelivery(Model,delivery,leadHours,now){if(!delivery||delivery.status==='sent')return null;const stale=new Date(now.getTime()-CLAIM_STALE_MS);return Model.findOneAndUpdate({_id:delivery._id,status:{$ne:'sent'},$or:[{claimedAt:null},{claimedAt:{$lt:stale}}]},{$set:{claimedAt:now,lastAttemptAt:now,leadHours}},{new:true}).lean();}
async function finishDelivery(Model,delivery,result,now){const success=result&&result.skipped===false&&Number(result.failed||0)===0;await Model.updateOne({_id:delivery._id},success?{$set:{status:'sent',sentAt:now,lastError:''},$unset:{claimedAt:1}}:{$set:{status:result?.failed?'failed':'pending',lastError:String(result?.reason||'Reminder email was not sent').slice(0,500)},$unset:{claimedAt:1}});return success;}
async function deliverAudience({booking,occurrence,audience,settings,merchantEmail='',now,ReminderModel}){const existing=await ensureDelivery(ReminderModel,booking,occurrence,audience,settings.reminderLeadHours);const claimed=await claimDelivery(ReminderModel,existing,settings.reminderLeadHours,now);if(!claimed)return{skipped:true,reason:'already-sent-or-claimed'};const current=bookingForOccurrence(booking,occurrence);const result=audience==='customer'?await sendCustomerUpcomingReminder(current,settings):await sendMerchantUpcomingReminder(current,settings,merchantEmail);await finishDelivery(ReminderModel,claimed,result,now);return result;}
export async function processUpcomingEmailReminders({now=new Date(),BookingModel=Booking,ShopModel=Shop,ReminderModel=EmailReminderDelivery}={}){const minDate=utcDateShift(now,-1),maxDate=utcDateShift(now,5);const bookings=await BookingModel.find({status:'confirmed',$or:[{date:{$gte:minDate,$lte:maxDate}},{'occurrences.date':{$gte:minDate,$lte:maxDate}}]}).select('_id shopId productTitle bookingMode date time slotKey occurrences duration timezone location staff customer status').limit(2000).lean();const shops=new Map();let sent=0,dueOccurrences=0;for(const booking of bookings){const key=String(booking.shopId||'');if(!shops.has(key))shops.set(key,await ShopModel.findById(booking.shopId).select('email emailSettings').lean());const shop=shops.get(key);const settings=normalizeEmailSettings(shop?.emailSettings||{});const merchantRecipients=merchantNotificationRecipients(settings,shop?.email||'');for(const occurrence of reminderOccurrences(booking)){const start=wallTimeToInstant(occurrence.date,occurrence.time,booking.timezone||'UTC');if(!reminderIsDue(start,settings.reminderLeadHours,now))continue;dueOccurrences+=1;if(settings.customerNotifications?.upcomingReminder!==false&&booking.customer?.email){const result=await deliverAudience({booking,occurrence,audience:'customer',settings,merchantEmail:shop?.email||'',now,ReminderModel});if(result?.skipped===false&&!result.failed)sent+=1;}if(settings.merchantNotifications?.upcomingReminder!==false&&merchantRecipients.length){const result=await deliverAudience({booking,occurrence,audience:'merchant',settings,merchantEmail:shop?.email||'',now,ReminderModel});if(result?.skipped===false&&!result.failed)sent+=1;}}}return{bookings:bookings.length,dueOccurrences,sent};}
export function startReminderScheduler(){let running=false,stopped=false;const run=async()=>{if(running||stopped)return;running=true;try{const result=await processUpcomingEmailReminders();if(result.sent)console.info('Appointment reminder emails sent.',result);}catch(error){console.error('Appointment reminder scheduler failed',error.message);}finally{running=false;}};const initial=setTimeout(run,INITIAL_DELAY_MS),interval=setInterval(run,RUN_INTERVAL_MS);initial.unref?.();interval.unref?.();return{run,stop(){stopped=true;clearTimeout(initial);clearInterval(interval);}};}
